version: '3'

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  proxy:
    image: traefik
    command: --web --docker --docker.domain=aim.loc --logLevel=DEBUG
    networks:
      - proxy
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    restart:
      always

  owncloud:
    image: imkulikov/nginx-sticky
    labels:
      - traefik.backend=app
      - traefik.docker.network=proxy
      - traefik.port=80
      - traefik.frontend.passHostHeader=true
      - traefik.backend.loadbalancer.sticky=true
    links:
      - owncloud-app-1
    volumes:
      - /opt/data/owncloud:/var/www/html:z
      - /opt/docker-compose/nginx/default.conf:/etc/nginx/conf.d/03-default.conf
    networks:
      - internal
      - proxy

  owncloud-app-1:
    image: owncloud:${VERSION}
    labels:
      - traefik.enable=false
    environment:
      - OWNCLOUD_DOMAIN=${DOMAIN}
      - OWNCLOUD_DB_TYPE=${DB_TYPE}
      - OWNCLOUD_DB_NAME=${DB_NAME}
      - OWNCLOUD_DB_USERNAME=${DB_USERNAME}
      - OWNCLOUD_DB_PASSWORD=${DB_PASSWORD}
      - OWNCLOUD_DB_HOST=${DB_HOST}
      - OWNCLOUD_ADMIN_USERNAME=${ADMIN_USERNAME}
      - OWNCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - OWNCLOUD_REDIS_ENABLED=${REDIS_ENABLED}
      - OWNCLOUD_REDIS_HOST=${REDIS_HOST}
    links:
      - db
      - redis
    volumes:
      - /opt/data/owncloud:/var/www/html:z
    networks:
      - internal
    restart: always

  owncloud-app-2:
    image: owncloud:${VERSION}
    labels:
      - traefik.enable=false
    environment:
      - OWNCLOUD_DOMAIN=${DOMAIN}
      - OWNCLOUD_DB_TYPE=${DB_TYPE}
      - OWNCLOUD_DB_NAME=${DB_NAME}
      - OWNCLOUD_DB_USERNAME=${DB_USERNAME}
      - OWNCLOUD_DB_PASSWORD=${DB_PASSWORD}
      - OWNCLOUD_DB_HOST=${DB_HOST}
      - OWNCLOUD_ADMIN_USERNAME=${ADMIN_USERNAME}
      - OWNCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - OWNCLOUD_REDIS_ENABLED=${REDIS_ENABLED}
      - OWNCLOUD_REDIS_HOST=${REDIS_HOST}
    links:
      - db
      - redis
    volumes:
      - /opt/data/owncloud:/var/www/html:z
    networks:
      - internal
    restart: always

  db: 
    image: webhippie/mariadb
    labels:
      - traefik.enable=false
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_USERNAME=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_PASSWORD}
    volumes:
      - /opt/data/mysql:/var/lib/mysql:z
    networks:
      - internal

  redis:
    image: webhippie/redis
    labels:
      - traefik.enable=false
    networks:
      - internal


