#!/bin/sh

### BEGIN INIT INFO
# Provides:       owncloud-docker
# Required-Start:    $local_fs $remote_fs $network $syslog $named 
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts owncloud-docker
# Description:       starts owncloud-docker using start-stop-daemon
### END INIT INFO

RETVAL=0

start () {
    /opt/docker-compose/owncloud/scripts/start.sh
}

stop () {
    /opt/docker-compose/owncloud/scripts/stop.sh
}

logs () {
    /opt/docker-compose/owncloud/scripts/logs.sh
}


case "$1" in
    start)
        start "$@"
        ;;
    stop)
        stop "$@"
        ;;
    restart)
        stop "$@"
        start "$@"
        ;;
    *)
        RETVAL=$?
esac
exit 0
